version: "3.9"
services:
  fast:
    build:
      context: .
      dockerfile: Dockerfile
    image: fast:v1
    tty: true
    stdin_open: true
    restart: unless-stopped
    command: "fast"
    volumes:
      - ".:/code:z"
